version: '3'

services:
  mysqldb:
    image:mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: P@ssw0rd2021
      - MYSQL_USER: steven
      - MYSQL_PASSWORD: stevenP@ssw0rd2021
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - steven-network
      
  wordpress:
    depends_on:
      - mysqldb
    image: wordpress:5.8.2-fpm-alpine
    container_name: wordpress
    deploy:
      replicas: 2
    restart: always
    environment:
      - WORDPRESS_DB_HOST: mysqldb:3306
      - WORDPRESS_DB_USER: steven
      - WORDPRESS_DB_PASSWORD: stevenP@ssw0rd2021
      - WORDPRESS_DB_NAME: stevenwordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - steven-network
  
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.4-alpine
    container_name: webserver
    deploy:
      replicas: 2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - steven-network
      
  # for SSL renewal using let's encrypt
  # certbot will fail if no subdomain (stevenwordpress) added to the domain (stevenweb.com)
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email steven@stevenweb.com --agree-tos --no-eff-email --force-renewal -d stevenwordpress.stevenweb.com

# to persist certbot, wordpress and mysql data
volumes:
  certbot-etc:
  wordpress:
  dbdata:

# wordpress, db, webserver and certbot using same network to communicate.
networks:
  steven-network:
    driver: bridge